log:
  exp_dir: trainResults/eardataset_nonrigid_randSurface_randrot
  log_freq: 8

model:
  num_layers: 4 
  in_points_dim: 3
  first_feats_dim: 256
  final_feats_dim: 32
  first_subsampling_dl: 0.3
  in_feats_dim: 1
  conv_radius: 4.25
  deform_radius: 5.0 
  num_kernel_points: 15
  KP_extent: 2.0
  KP_influence: linear
  aggregation_mode: sum 
  fixed_kernel_points: center
  use_batch_norm: True 
  batch_norm_momentum: 0.02

overlap_attention_module:
  gnn_feats_dim: 256 
  dgcnn_k: 10
  num_head: 4
  ppf_k: 64
  radius_mul: 32
  bottleneck: True
  nets: ['gge','cross_attn','gge']

loss:
  pos_margin: 0.1
  neg_margin: 1.4
  log_scale: 16
  pos_radius: 0.21
  safe_radius: 0.75
  overlap_radius: 0.45
  matchability_radius: 0.3 
  w_circle_loss: 1.0
  w_overlap_loss: 1.0
  w_saliency_loss: 0.0
  max_points: 512

optimiser:
  optimizer: SGD
  max_epoch: 150
  lr: 0.05
  weight_decay: 0.000001
  momentum: 0.98
  scheduler: ExpLR
  # scheduler: CosA
  T_0: 10
  T_mult: 4
  eta_min: 0.00001
  scheduler_gamma: 0.99
  scheduler_freq: 1
  iter_size: 1

dataset:
  dataset: eardataset
  benchmark: 3DMatch
  root: mesh_dataset/ear_dataset
  batch_size: 1
  noisy_intra: True
  num_workers: 0
  augment_noise: 0.000
