gpu_mode: True
deformation_model: NSFP

use_ldmk: False

use_depth: False


#optimization
iters: &iters 5000
lr: 0.01
momentum: 0.9
weight_decay: 0.0001
max_break_count: 70
break_threshold_ratio: 0.001


samples: 2000


#dataset
data_root : "data/split/"
split: { 'test': "4DMatch-F" }


#experimen
exp_dir :  outlier
folder: NSFP